export enum PROJECT_PERMISSION {
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  TASK_MANAGE = 'TASK_MANAGE',
  ROLE_MANAGE = 'ROLE_MANAGE',
  MEMBER_MANAGE = 'MEMBER_MANAGE',
  MESSAGE_VIEW = 'MESSAGE_VIEW',
  MESSAGE_SEND = 'MESSAGE_SEND',
  FILE_MANAGE = 'FILE_MANAGE',
}
